# Generated by Django 3.1.5 on 2021-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID ответа')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('goto', models.PositiveIntegerField(verbose_name='Ссылка на следующий вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('message_before_question', models.TextField(blank=True, verbose_name='Сопутствующее сообщение перед вопросом')),
                ('answers', models.ManyToManyField(related_name='answers_for_questions', to='mainApi.Answer', verbose_name='Ответы на вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
