# Generated by Django 3.1.5 on 2021-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0003_auto_20210109_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
