# Generated by Django 3.1.5 on 2021-02-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0004_remove_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='answerslist',
        ),
    ]
