# Generated by Django 3.1.5 on 2021-02-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0005_auto_20210224_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerslist',
            new_name='answers',
        ),
    ]
