# Generated by Django 3.1.5 on 2021-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0006_auto_20210224_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images', verbose_name='Выберите своё изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='mainApi.Answer', verbose_name='Ответы на вопрос'),
        ),
    ]
