# Generated by Django 3.1.5 on 2021-03-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0007_auto_20210315_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
